FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install software-properties-common -y
RUN apt-cache search php7.1
# RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php -y
# RUN apt-get update
# RUN apt-get install php7.1 -y
# RUN apt-get install libapache2-mod-php7.1 -y --allow-unauthenticated
# RUN apt-get install apache2 php7.1-mysql php7.1-intl php7.1-opcache php7.1-mcrypt php7.1-gd php7.1-curl php7.1-cli php7.1-fpm php7.1-imap php7.1-json php7.1-xml php7.1-mbstring -y
# RUN apt-get install sendmail-bin curl -y
# RUN apt-get install vim -y
# RUN apt-get install php7.1-memcached -y
# RUN apt-get install unattended-upgrades
# RUN service unattended-upgrades start
# RUN apt-get update
# RUN apt-get install vim -y
# RUN apt-get install mailutils -y
# RUN apt-get install htop -y

# RUN a2enmod rewrite headers ssl
# RUN a2enmod deflate expires

# CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
